#!/usr/bin/env python3
import urllib.request
import json
import os
import sys

URL = "https://raw.githubusercontent.com/mwgg/Airports/master/airports.json"
CACHE_PATH = os.path.join(os.path.dirname(__file__), "airports.json")
OUTPUT_HEADER = os.path.abspath(os.path.join(os.path.dirname(__file__), "../src/airports_data.h"))

print("Checking airport database...")
if not os.path.exists(CACHE_PATH):
    print(f"Downloading from {URL}...")
    req = urllib.request.Request(URL, headers={"User-Agent": "ESP32-Flight-Globe-Builder/1.0"})
    with urllib.request.urlopen(req) as resp, open(CACHE_PATH, "wb") as f:
        f.write(resp.read())

with open(CACHE_PATH, "r", encoding="utf-8") as f:
    raw_data = json.load(f)

airports = {}
for icao, info in raw_data.items():
    iata = info.get("iata", "").strip().upper()
    if len(iata) == 3 and iata.isalpha():
        try:
            lat = float(info["lat"])
            lon = float(info["lon"])
            if -90.0 <= lat <= 90.0 and -180.0 <= lon <= 180.0:
                airports[iata] = {
                    "iata": iata,
                    "lat": lat,
                    "lon": lon,
                    "name": info.get("name", "").replace('"', '')
                }
        except (ValueError, KeyError):
            pass

# Ensure critical test airports are verified
critical_airports = {
    "ORD": (41.9786, -87.9048, "Chicago O'Hare"),
    "CMI": (40.0392, -88.2781, "Willard Airport Champaign"),
    "JFK": (40.6398, -73.7789, "New York JFK"),
    "SFO": (37.6190, -122.3750, "San Francisco"),
    "LHR": (51.4706, -0.4619, "London Heathrow"),
    "HND": (35.5523, 139.7800, "Tokyo Haneda"),
    "DXB": (25.2528, 55.3644, "Dubai International"),
    "SYD": (-33.9461, 151.1770, "Sydney Kingsford Smith"),
    "LAX": (33.9425, -118.4081, "Los Angeles"),
    "ATL": (33.6407, -84.4277, "Atlanta Hartsfield")
}

for code, (lat, lon, name) in critical_airports.items():
    airports[code] = {"iata": code, "lat": lat, "lon": lon, "name": name}

sorted_codes = sorted(airports.keys())
print(f"Total unique valid IATA airports: {len(sorted_codes)}")

with open(OUTPUT_HEADER, "w", encoding="utf-8") as out:
    out.write("""// Auto-generated IATA Airport Database
// Do not edit manually - generated by tools/generate_airports.py
#pragma once
#include <Arduino.h>
#include <cstring>
#include <cstdlib>

#pragma pack(push, 1)
struct AirportRecord {
    char iata[4];        // Null-terminated 3-letter IATA code
    int16_t lat_x100;    // Latitude * 100 (-9000 to +9000)
    int16_t lon_x100;    // Longitude * 100 (-18000 to +18000)
};
#pragma pack(pop)

static const AirportRecord AIRPORT_DATABASE[] PROGMEM = {
""")
    for code in sorted_codes:
        info = airports[code]
        lat_i = int(round(info["lat"] * 100))
        lon_i = int(round(info["lon"] * 100))
        out.write(f'    {{"{code}", {lat_i}, {lon_i}}},\n')

    out.write(f"""}};

static const size_t AIRPORT_DATABASE_COUNT = {len(sorted_codes)};

// Binary search lookup for airport by 3-letter IATA code
inline const AirportRecord* findAirportInDB(const char* code) {{
    if (!code || strlen(code) < 3) return nullptr;
    char target[4];
    for (int i = 0; i < 3; i++) {{
        char c = code[i];
        if (c >= 'a' && c <= 'z') c -= 32;
        target[i] = c;
    }}
    target[3] = '\\0';

    int low = 0;
    int high = (int)AIRPORT_DATABASE_COUNT - 1;
    while (low <= high) {{
        int mid = low + (high - low) / 2;
        AirportRecord rec;
        memcpy_P(&rec, &AIRPORT_DATABASE[mid], sizeof(AirportRecord));
        int cmp = strcmp(target, rec.iata);
        if (cmp == 0) {{
            return &AIRPORT_DATABASE[mid];
        }} else if (cmp < 0) {{
            high = mid - 1;
        }} else {{
            low = mid + 1;
        }}
    }}
    return nullptr;
}}

inline bool getAirportCoords(const char* code, float& outLat, float& outLon) {{
    const AirportRecord* ptr = findAirportInDB(code);
    if (!ptr) return false;
    AirportRecord rec;
    memcpy_P(&rec, ptr, sizeof(AirportRecord));
    outLat = rec.lat_x100 / 100.0f;
    outLon = rec.lon_x100 / 100.0f;
    return true;
}}
""")

print(f"Successfully generated {OUTPUT_HEADER} ({os.path.getsize(OUTPUT_HEADER):,} bytes)")
